parameters:
    oh_form_error_log.listener.class:       Oh\FormErrorLogBundle\EventListener\ErrorLogSubscriber
    oh_form_error_log.logger.class:	        Oh\FormErrorLogBundle\Logger\Logger
    oh_form_error_log.db.class:	            Oh\FormErrorLogBundle\Logger\DatabaseLogger
    oh_form_error_log.db.entity.class:	    Oh\FormErrorLogBundle\Entity\FormErrorLogEntityInterface

services:
    oh_form_error_log.logger.db:
        class:            %oh_form_error_log.db.class%
        arguments:        [@doctrine.orm.default_entity_manager, %oh_form_error_log.db.entity.class%]
    oh_form_error_log.logger:
        class:            %oh_form_error_log.logger.class%
        arguments:        [@logger]
        tags:
            - { name: monolog.logger, channel: formerror }
    oh_form_error_log.listener.db:
        class:            %oh_form_error_log.listener.class%
        arguments:        [@oh_form_error_log.logger.db, @request]
        scope: request
    oh_form_error_log.listener:
        class:            %oh_form_error_log.listener.class%
        arguments:        [@oh_form_error_log.logger, @request]
        scope: request
